---
services:
  timescaledb:
    image: timescale/timescaledb:${TIMESCALEDB_IMAGE_VERSION}
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      start_period: 10s
      interval: 10s
      retries: 5
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate:${MIGRATE_IMAGE_VERSION}
    depends_on:
      timescaledb:
        condition: service_healthy
    command:
      - -path
      - /migrations
      - -database
      - postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescaledb:5432/${POSTGRES_DB}?sslmode=disable
      - -verbose
      - up
    volumes:
      - ./migrations:/migrations
